name: JIRENGU_CI

on: pull_request_target
jobs:
  homework-judgement:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
              🎉 感谢您提交Pull Request！请稍等片刻，我们已经将其提交到CI进行检查，一旦有结果会立即通知您！
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: automerge
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Comment PR if tests pass
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'All tests passed! 🎉 Congratulation!🎉🎉🎉 We will revert your commit '
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Comment PR if tests fail
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'Some tests failed. 😞 Please check the [ci logs](${{ github.event.pull_request._links.html.href }}/checks) for more details.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge PR if tests pass
        if: ${{ success() }}
        run: |
          # Merge PR
          curl -X PUT -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge

      - name: Revert PR if merged
        if: ${{ success() }}
        run: |
          # Set up git credentials with MY_TOKEN
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

          # Checkout the main branch
          git fetch origin ${{ github.event.repository.default_branch }}:${{ github.event.repository.default_branch }}
          git checkout ${{ github.event.repository.default_branch }}
    
          # Revert the merge commit
          git revert -m 1 ${{ github.sha }}
    
          # Push the revert commit with MY_TOKEN
          git remote set-url --push origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository }}
          git push origin ${{ github.event.repository.default_branch }}  
      
